### ISSUE TITLE
Throwing abunch of exeptions. 

### ISSUE THREAD

**Issue by cj1705** [CuzIm1Tigaaa/Spectator#2]
HI!

After about 11 hours of the server running, The server started to spam exceptions from the plugin. I'm running 1.17.1 paper

Heres what I get
 [Spectator] Task #12223083 for Spectator v1.6.10.1 generated an exception
java.lang.StackOverflowError: null
	at me.lucko.luckperms.common.context.manager.ContextManager.getCalculatorClass(ContextManager.java:206) ~[?:?]
	at me.lucko.luckperms.common.context.manager.ContextManager.callContextCalculator(ContextManager.java:142) ~[?:?]
	at me.lucko.luckperms.common.context.manager.ContextManager.calculate(ContextManager.java:159) ~[?:?]
	at me.lucko.luckperms.common.context.manager.QueryOptionsCache.supply(QueryOptionsCache.java:54) ~[?:?]
	at me.lucko.luckperms.common.context.manager.QueryOptionsCache.supply(QueryOptionsCache.java:42) ~[?:?]
	at me.lucko.luckperms.common.cache.ExpiringCache.get(ExpiringCache.java:64) ~[?:?]
	at me.lucko.luckperms.common.context.manager.QueryOptionsCache.getQueryOptions(QueryOptionsCache.java:59) ~[?:?]
	at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible.hasPermission(LuckPermsPermissible.java:175) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:212) ~[patched_1.17.1.jar:git-Paper-408]
	at de.cuzim1tigaaa.spectator.cycle.Cycle.lambda$updateLists$1(Cycle.java:50) ~[Spectator-1.6.10.1.jar:?]
	at java.util.ArrayList.removeIf(ArrayList.java:1672) ~[?:?]
	at java.util.ArrayList.removeIf(ArrayList.java:1660) ~[?:?]
	at de.cuzim1tigaaa.spectator.cycle.Cycle.updateLists(Cycle.java:50) ~[Spectator-1.6.10.1.jar:?]
	at de.cuzim1tigaaa.spectator.cycle.Cycle.getNextPlayer(Cycle.java:29) ~[Spectator-1.6.10.1.jar:?]
	at de.cuzim1tigaaa.spectator.cycle.Cycle.getNextPlayer(Cycle.java:33) ~[Spectator-1.6.10.1.jar:?]
	at de.cuzim1tigaaa.spectator.cycle.Cycle.getNextPlayer(Cycle.java:33) ~[Spectator-1.6.10.1.jar:?]
	at de.cuzim1tigaaa.spectator.cycle.Cycle.getNextPlayer(Cycle.java:33) ~[Spectator-1.6.10.1.jar:?]
	at de.cuzim1tigaaa.spectator.cycle.Cycle.getNextPlayer(Cycle.java:33) ~[Spectator-1.6.10.1.jar:?]

This spams untill the server crashed. This also prevented from people from joining. The server crashing might not be from this since it was not in the thread dump but I thought it could be a possibility.

Any tips?

**Comment by cj1705** [comment]
I also noticed that it could be a conflict with luck perms? Could that be why its throwing it?

**Comment by CuzIm1Tigaaa** [comment]
I don't think that luckperms itself is the problem, I'll have a look at the problem
Can you maybe add a timings report? This might help

**Comment by cj1705** [comment]
Thanks for writing back, I currently don't have access to the timings report but, we had the interval set to 15 seconds.

**Comment by CuzIm1Tigaaa** [comment]
hm okay... My first thought was, that the interval was too short, but 15 seems quite long to me 😄
I might have an idea on the error though, will test it in the next days.

**Comment by CuzIm1Tigaaa** [comment]
I think this should be fixed in the next version.
