### ISSUE TITLE
`/speccyle` somehow broken

### ISSUE THREAD

**Issue by cupang-afk** [CuzIm1Tigaaa/Spectator#22]
```log
[21:14:59 INFO]: cupang_afk issued server command: /speccycle start 10 random
[21:14:59 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'speccycle' in plugin Spectator v2.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1001) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:452) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:353) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2305) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$17(ServerGamePacketListenerImpl.java:2265) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1485) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1462) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1385) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1363) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2113]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.equals(Object)" because "last" is null
        at de.cuzim1tigaaa.spectator.cycle.CycleTask.selectNextPlayer(CycleTask.java:104) ~[Spectator-[SpigotMC-2.0].jar:?]
        at de.cuzim1tigaaa.spectator.cycle.CycleTask.startTask(CycleTask.java:43) ~[Spectator-[SpigotMC-2.0].jar:?]
        at de.cuzim1tigaaa.spectator.spectate.SpectateUtils.StartCycle(SpectateUtils.java:183) ~[Spectator-[SpigotMC-2.0].jar:?]
        at de.cuzim1tigaaa.spectator.commands.SpectateCycle.startSpectateCycle(SpectateCycle.java:116) ~[Spectator-[SpigotMC-2.0].jar:?]
        at de.cuzim1tigaaa.spectator.commands.SpectateCycle.onCommand(SpectateCycle.java:61) ~[Spectator-[SpigotMC-2.0].jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more
```

using spectator 2.0
```log
[21:08:34 INFO]: Checking version, please wait...
[21:08:35 INFO]: Current: git-Purpur-2113 (MC: 1.20.4)*
Previous: git-Purpur-2114 (MC: 1.20.4)
* You are 5 version(s) behind
Download the new version at: https://purpurmc.org/download
```

extra note:
the boss bar still present after the command crash
relog fix it
![image](https://github.com/CuzIm1Tigaaa/Spectator/assets/66926348/0118cc93-ce66-43eb-9c85-530545c1eb76)

**Comment by CuzIm1Tigaaa** [comment]
Hey
thanks for reporting. I already fixed this but I did not had the time to publish this.
Will be done in the next days.

**Comment by CuzIm1Tigaaa** [comment]
As locally tested, this problem should now be fixed. Please let me know if this is still a problem.
